# Generated by Django 5.2.7 on 2025-10-20 14:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('active', 'Đang hoạt động'), ('locked', 'Đã khóa'), ('cancelled', 'Đã hủy')], default='active', max_length=20)),
                ('duration_minutes', models.IntegerField(help_text='Thời lượng cuộc họp từ 15 phút đến 8 giờ', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(480)], verbose_name='Thời lượng (phút)')),
                ('timezone', models.CharField(default='Asia/Ho_Chi_Minh', max_length=50, verbose_name='Múi giờ mặc định')),
                ('date_range_start', models.DateField(verbose_name='Ngày bắt đầu phạm vi')),
                ('date_range_end', models.DateField(verbose_name='Ngày kết thúc phạm vi')),
                ('work_hours_start', models.TimeField(default='09:00:00', verbose_name='Giờ làm việc bắt đầu')),
                ('work_hours_end', models.TimeField(default='18:00:00', verbose_name='Giờ làm việc kết thúc')),
                ('step_size_minutes', models.IntegerField(choices=[(15, '15 phút'), (30, '30 phút'), (60, '60 phút')], default=30, verbose_name='Bước quét')),
                ('work_days_only', models.BooleanField(default=True, help_text='Chỉ tìm kiếm trong các ngày Thứ 2 - Thứ 6', verbose_name='Chỉ ngày làm việc')),
                ('hide_participant_names', models.BooleanField(default=False, verbose_name='Ẩn tên người tham gia')),
                ('response_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Hạn chót trả lời')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_email', models.EmailField(blank=True, max_length=254, verbose_name='Email người tạo')),
            ],
            options={
                'db_table': 'meeting_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='meeting_req_token_a741d7_idx'), models.Index(fields=['status', 'created_at'], name='meeting_req_status_39e8aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Tên')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('timezone', models.CharField(default='Asia/Ho_Chi_Minh', max_length=50, verbose_name='Múi giờ')),
                ('has_responded', models.BooleanField(default=False)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.meetingrequest')),
            ],
            options={
                'db_table': 'participants',
            },
        ),
        migrations.CreateModel(
            name='BusySlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(verbose_name='Thời gian bắt đầu (UTC)')),
                ('end_time', models.DateTimeField(verbose_name='Thời gian kết thúc (UTC)')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busy_slots', to='meetings.participant')),
            ],
            options={
                'db_table': 'busy_slots',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='SuggestedSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(verbose_name='Thời gian bắt đầu (UTC)')),
                ('end_time', models.DateTimeField(verbose_name='Thời gian kết thúc (UTC)')),
                ('available_count', models.IntegerField(default=0, help_text='Number of participants available during this slot', verbose_name='Số người rảnh')),
                ('total_participants', models.IntegerField(default=0, verbose_name='Tổng số người')),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Leader has selected this slot as final', verbose_name='Đã chốt')),
                ('meeting_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_slots', to='meetings.meetingrequest')),
            ],
            options={
                'db_table': 'suggested_slots',
                'ordering': ['-available_count', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['meeting_request', 'has_responded'], name='participant_meeting_e7cfa9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('meeting_request', 'email')},
        ),
        migrations.AddIndex(
            model_name='busyslot',
            index=models.Index(fields=['participant', 'start_time', 'end_time'], name='busy_slots_partici_d8d596_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestedslot',
            index=models.Index(fields=['meeting_request', '-available_count'], name='suggested_s_meeting_9aceed_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestedslot',
            index=models.Index(fields=['meeting_request', 'is_locked'], name='suggested_s_meeting_438138_idx'),
        ),
    ]
