# Generated by Django 5.2.7 on 2025-10-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_alter_participant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrequest',
            name='creator_id',
            field=models.CharField(blank=True, help_text='Session/cookie-based identifier for the creator', max_length=100, verbose_name='ID người tạo'),
        ),
    ]
